Wip

diff --git a/.github/setup-dotnet/action.yml b/.github/setup-dotnet/action.yml
--- a/.github/setup-dotnet/action.yml
+++ b/.github/setup-dotnet/action.yml
@@ -38,3 +38,16 @@ runs:
           Get-Command dotnet
           dotnet --info
           echo "::endgroup::"
+
+    - name: Add dotnet to path
+      shell: pwsh
+      run: |
+        $DotnetPath = (Get-Command dotnet).Source
+        if ($DotnetPath -eq $null) {
+          Write-Error "Dotnet command not found. Ensure .NET is installed correctly."
+          exit 1
+        }
+
+        $DotnetPath = Split-Path $DotnetPath -Parent
+        Write-Host "Adding $DotnetPath to PATH"
+        Write-Host "$DotnetPath" >> "$GITHUB_PATH"
